### PR TITLE
Updates to Events Page, Admin Login page

### PR DESCRIPTION
**Pull request by oddoye**
Screenshot 2023-12-05 at 6 38 08 PM
Screenshot 2023-12-05 at 6 37 55 PM

### CODE REVIEW

**Comment by oddoye** [comment]
Screenshot 2023-12-05 at 6 43 35 PM
Screenshot 2023-12-05 at 6 43 30 PM
Screenshot 2023-12-05 at 6 43 38 PM

**Comment by oddoye** [comment]
Admin Login BG still not complete.

**Review by krepinnegga — APPROVED** [review]
Looks good to me

**Review by Ewabunmi — COMMENTED** [review]
Looks perfect now

**Pull request merged**
