### PR TITLE
Update to why we exist

### PR DESCRIPTION
**Pull request by Ewabunmi**
Update to why we exist
Sssscreen1
Papertown/assets/123972532/078896fa-221c-42a9-9bd8-e3617c3fe55c)
Ssscreeen2
n/assets/123972532/fe609d06-4e8a-462d-91f2-13cde435eb8f)
Scccccren11

Sssscreen3

### CODE REVIEW

**Review by Ewabunmi — COMMENTED** [review]
Great Job

**Comment by krepinnegga** [comment]
Looks Good to me

**Review by krepinnegga — APPROVED** [review]

**Review by EugeneSantaclausian — CHANGES_REQUESTED** [review]
The two white cards in the header should also have some padding around them when they are on the mobile view. Kindly update them as well. 
However I hope these changes do not affect how it looks on a desktop screen though.
CC: @Ewabunmi

**Comment by Ewabunmi** [comment]
Noted

**Review by EugeneSantaclausian — APPROVED** [review]

**Pull request merged**
