### PR TITLE
Events page complete

### PR DESCRIPTION
**Pull request by oddoye**
Screenshot 2023-11-28 at 12 17 05 PM
Screenshot 2023-11-28 at 12 16 58 PM
Screenshot 2023-11-28 at 12 16 54 PM
Screenshot 2023-11-28 at 12 16 51 PM

### CODE REVIEW

**Review by krepinnegga — APPROVED** [review]
Looks good to me. But next time when dealing with cards you should try mapping over a data object so you don't have to repeat code.

**Review by Ewabunmi — COMMENTED** [review]
Looks beautiful!

**Comment by oddoye** [comment]
The Events bg has been updated & homepage bg fixed.
Screenshot 2023-11-30 at 12 06 28 PM
Screenshot 2023-11-30 at 12 06 26 PM
Screenshot 2023-11-30 at 12 06 19 PM
Screenshot 2023-11-30 at 12 06 17 PM
Screenshot 2023-11-30 at 12 01 22 PM
Screenshot 2023-11-30 at 11 58 04 AM
Screenshot 2023-11-30 at 11 57 52 AM
Screenshot 2023-11-30 at 11 57 42 AM
Screenshot 2023-11-30 at 11 57 40 AM

**Review by Nelson877 — COMMENTED** [review]
Please  can you work on the card for the mobile view

**Pull request merged**
